runtime: java17
service: default
instance_class: F1

# Spring Boot serves static files from src/main/resources/static automatically.
# No handlers block is needed for Java 17 Standard.

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.7

env_variables:
  # Web3Forms UUID (string). Quotes are fine; no spaces inside the UUID.
  WEB3FORMS_ACCESS_KEY: "bbf8ebfd-a4ae-4023-bb7e-24712ad6bac3"
